site_name: DPLMP Lua Reference

nav:
  - Home: index.md
  - Client: 
    - Index: client/index.md
    - Classes: 
      - Character: client/Classes/Character.md
    - Libraries:
      - Core: client/Libraries/Core.md
      - CharacterManager: client/Libraries/CharacterManager.md
      
theme: readthedocs